# Use Python 3.10 base image
FROM python:3.10-slim-bullseye

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Install system dependencies including for psql if we want it
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    gcc \
    libpq-dev \
    libc-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

RUN pip install pytest pytest-cov httpx pytest-asyncio

# Copy the FastAPI scripts into the container
COPY . .

# Expose port 4000
EXPOSE 4000

CMD ["pytest", "--doctest-modules", "--junitxml=junit/test-results.xml", "--cov=com", "--cov-report=xml", "--cov-report=html"]